//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXFTSMArchiver.TSMArchiver {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IWebService.SoapFaultBase", Namespace="http://schemas.datacontract.org/2004/07/TSMarchiver")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MXFTSMArchiver.TSMArchiver.IWebServiceMxfServerFault))]
    public partial class IWebServiceSoapFaultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IWebService.MxfServerFault", Namespace="http://schemas.datacontract.org/2004/07/TSMarchiver")]
    [System.SerializableAttribute()]
    public partial class IWebServiceMxfServerFault : MXFTSMArchiver.TSMArchiver.IWebServiceSoapFaultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ErrorParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ErrorParameters {
            get {
                return this.ErrorParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorParametersField, value) != true)) {
                    this.ErrorParametersField = value;
                    this.RaisePropertyChanged("ErrorParameters");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://filmpartners.nl/TSMarchiver/", ConfigurationName="TSMArchiver.TSMarchiver")]
    public interface TSMarchiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doArchiveProject", ReplyAction="http://filmpartners.nl/TSMarchiver/TSMarchiver/doArchiveProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MXFTSMArchiver.TSMArchiver.IWebServiceMxfServerFault), Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doArchiveProjectMxfServerFaultFaul" +
            "t", Name="IWebService.MxfServerFault", Namespace="http://schemas.datacontract.org/2004/07/TSMarchiver")]
        void doArchiveProject(int ProjectID, string StartTimestamp, int ClientID, bool deleteFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doArchiveProject", ReplyAction="http://filmpartners.nl/TSMarchiver/TSMarchiver/doArchiveProjectResponse")]
        System.Threading.Tasks.Task doArchiveProjectAsync(int ProjectID, string StartTimestamp, int ClientID, bool deleteFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doRetreiveProject", ReplyAction="http://filmpartners.nl/TSMarchiver/TSMarchiver/doRetreiveProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MXFTSMArchiver.TSMArchiver.IWebServiceMxfServerFault), Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doRetreiveProjectMxfServerFaultFau" +
            "lt", Name="IWebService.MxfServerFault", Namespace="http://schemas.datacontract.org/2004/07/TSMarchiver")]
        void doRetreiveProject(int ProjectID, string StartTimestamp, int ClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://filmpartners.nl/TSMarchiver/TSMarchiver/doRetreiveProject", ReplyAction="http://filmpartners.nl/TSMarchiver/TSMarchiver/doRetreiveProjectResponse")]
        System.Threading.Tasks.Task doRetreiveProjectAsync(int ProjectID, string StartTimestamp, int ClientID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TSMarchiverChannel : MXFTSMArchiver.TSMArchiver.TSMarchiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSMarchiverClient : System.ServiceModel.ClientBase<MXFTSMArchiver.TSMArchiver.TSMarchiver>, MXFTSMArchiver.TSMArchiver.TSMarchiver {
        
        public TSMarchiverClient() {
        }
        
        public TSMarchiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSMarchiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSMarchiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSMarchiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void doArchiveProject(int ProjectID, string StartTimestamp, int ClientID, bool deleteFiles) {
            base.Channel.doArchiveProject(ProjectID, StartTimestamp, ClientID, deleteFiles);
        }
        
        public System.Threading.Tasks.Task doArchiveProjectAsync(int ProjectID, string StartTimestamp, int ClientID, bool deleteFiles) {
            return base.Channel.doArchiveProjectAsync(ProjectID, StartTimestamp, ClientID, deleteFiles);
        }
        
        public void doRetreiveProject(int ProjectID, string StartTimestamp, int ClientID) {
            base.Channel.doRetreiveProject(ProjectID, StartTimestamp, ClientID);
        }
        
        public System.Threading.Tasks.Task doRetreiveProjectAsync(int ProjectID, string StartTimestamp, int ClientID) {
            return base.Channel.doRetreiveProjectAsync(ProjectID, StartTimestamp, ClientID);
        }
    }
}
